verbose: False
# DDM simulation parameters
ddm_params:
  starting_point: 0.5    # bias, z
  boundary: 1.0          # decision boundary, a
  tnd: 0.2               # non-decision time, Ter
  drift: 0.5             # drift rate, v
  diffusion: 1.0         # diffusion rate, s

# PyBeam simulation parameters
simulation_params:
  load_rt_data: False
  load_traces: False
  save_rt_data: True
  save_traces: False
  rt_data_path: ''
  path_pybeam_model: 'ddm/custom_models/get_traces'
  n_sims: 1024

# RNN setup
rnn_params:
  batch_size: 1024
  hidden_dim: 16
  hidden_layers: 0
  min_dt: 0.01
  max_dt: 0.01
  max_steps: 100
  warmup: 10

# Training setup
training_params:
  checkpoint: False
  checkpoint_load_path: ''
  epochs: 1024
  lr: 0.0003
  lr_schedule: True
  learn_threshold: False
  train_test_ratio: 10.
  plot_interval: 100
  early_stopping: True
  patience: 10
  device: cpu
  dropout: 0.15
  weight_decay: 0.0001

# SINDy setup
sindy_params:
  run_sindy: True
  training:
    poly_order: 2
    threshold: 0.1  # SINDy sparsity threshold
    ensemble: True
    library_ensemble: True
    dt_default: 0.01
    fit_intercept: False
    discrete_time: True

debug_params:
  print_gradients: False